name: ubite
description: My custom unverified Bazzite-deck gaming layer fork

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - papirus-icon-theme
      - sassc

  # Switch the broken copy module out for clean, raw script instructions
  - type: containerfile
    containerfile: |
      COPY themes/ /usr/share/themes/
