name: ubite
description: My custom unverified Bazzite-deck gaming layer fork

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - papirus-icon-theme
      - sassc

  # Correct schema structure using 'snippets:' for containerfile blocks
  - type: containerfile
    snippets:
      - COPY themes/ /usr/share/themes/
