name: Build Ubite
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Custom Image via BlueBuild
        uses: blue-build/github-action@v1
        with:
          # Tell BlueBuild exactly where your file lives
          recipe: 'recipe.yml'
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          pr_event_number: ${{ github.event.number }}
          build_opts: '--no-sign'
